In [1]:
import tensorflow as tf
import numpy as np

from tensorflow import Tensor, Variable
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense

In [2]:
# 标量
a: Tensor = tf.constant(1.2)
aa: Tensor = tf.constant(np.array(1.2))
print(a)
print(aa)

# 常用属性
print("==属性==")
print(a.shape)
print(a.numpy())
print(a.dtype)

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(1.2, shape=(), dtype=float64)
==属性==
()
1.2
<dtype: 'float32'>


In [3]:
# 向量
b: Tensor = tf.constant([1., 2.], dtype=tf.float64)
bb: Tensor = tf.constant(np.array([1., 2.]))
print(b)
print(bb)

# 常用属性
print("==属性==")
print(b.shape)
print(b.numpy())
print(b.dtype)

tf.Tensor([1. 2.], shape=(2,), dtype=float64)
tf.Tensor([1. 2.], shape=(2,), dtype=float64)
==属性==
(2,)
[1. 2.]
<dtype: 'float64'>


In [4]:
# 矩阵
c: Tensor = tf.constant([[1, 2], [3, 4]])
cc: Tensor = tf.constant(np.array([[1, 2], [3, 4]]))
print(c)
print(cc)

# 常用属性
print("==属性==")
print(c.shape)
print(c.numpy())
print(c.dtype)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)
==属性==
(2, 2)
[[1 2]
 [3 4]]
<dtype: 'int32'>


In [5]:
# bool

d: Tensor = tf.constant(True)
print(d)

tf.Tensor(True, shape=(), dtype=bool)


In [6]:
# 类型转换

e: Tensor = tf.constant(5, dtype=tf.int16)
print(f"before: {e.dtype}")
ee: Tensor = tf.cast(e, tf.int32)
print(f"after: {ee.dtype}")

before: <dtype: 'int16'>
after: <dtype: 'int32'>


In [7]:
f: Tensor = tf.constant([-1, 0, 1, 2])

ff: Variable = tf.Variable(f)

print(ff)

# 属性
print(f"name: {ff.name} trainable: {ff.trainable}")

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([-1,  0,  1,  2], dtype=int32)>
name: Variable:0 trainable: True


In [8]:
g1: Tensor = tf.convert_to_tensor([1. ,2.])
g2: Tensor = tf.convert_to_tensor(np.array([1., 2.]))
    
print(g1)
print(g2)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
tf.Tensor([1. 2.], shape=(2,), dtype=float64)


In [9]:
# 创建全0 全1的向量
h1: Tensor = tf.zeros([2, 2])
h2: Tensor = tf.ones([2, 2])
print(f"h1: {h1}")
print(f"h2: {h2}")

print("=======================")

h3: Tensor = tf.zeros_like(h2)
h4: Tensor = tf.ones_like(h1)
print(f"h3: {h3}")
print(f"h4: {h4}")

print("=======================")

# 创建自定义数值的张量
h5: Tensor = tf.fill([1], -1)   # 第一个参数是维度, 第二个参数是数值
h6: Tensor = tf.fill([2,2], 99)
print(f"h5: {h5}")
print(f"h6: {h6}")

h1: [[0. 0.]
 [0. 0.]]
h2: [[1. 1.]
 [1. 1.]]
h3: [[0. 0.]
 [0. 0.]]
h4: [[1. 1.]
 [1. 1.]]
h5: [-1]
h6: [[99 99]
 [99 99]]


In [10]:
# ragged tesnor, 用于创建不规则的向量
r = tf.ragged.constant([[11, 12], [21, 22, 23], [], [4]])
print(r)
print(r[1])
print(r[1: 2])

# ops on ragged tensor
r2 = tf.ragged.constant([[11, 12], [21, 22, 23], []])
print(tf.concat([r, r2], axis=0))       

# ragged转化为tensor时会填充0
print(r.to_tensor())

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [4]]>
tf.Tensor([21 22 23], shape=(3,), dtype=int32)
<tf.RaggedTensor [[21, 22, 23]]>
<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [4], [11, 12], [21, 22, 23], []]>
tf.Tensor(
[[11 12  0]
 [21 22 23]
 [ 0  0  0]
 [ 4  0  0]], shape=(4, 3), dtype=int32)


In [11]:
# sparse tensor

s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2 ,3]],
                   values=[1., 2., 3.], 
                   dense_shape=[3, 4])
print(s)
# 转化为密集矩阵
# 注意indices的必须是排好序的，才能进行to_dense操作
print(tf.sparse.to_dense(s))

s2 = s * 2.
print(s2, "\n")

s4 = tf.constant([[10., 20.],
                  [30., 40.],
                  [50., 60.],
                  [70., 80.]])

print(tf.sparse.sparse_dense_matmul(s, s4))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)
SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]], shape=(3, 2), dtype=float32)


In [12]:
# 创建已知维度的张量

# 标准正态分布
i1: Tensor = tf.random.normal([2, 2])
print(f"i1: {i1}")

# 正态分布
i2: Tensor = tf.random.normal([2, 2], mean=1, stddev=2)
print(f"i2: {i2}")

# 均匀分布
i3: Tensor = tf.random.uniform([2, 4], minval=3, maxval=5)
print(f"i3: {i3}")

i1: [[-0.37044877 -0.2163778 ]
 [ 1.1580064  -0.01384553]]
i2: [[0.6642258 2.967782 ]
 [2.3019896 2.0377908]]
i3: [[3.5886955 4.6388507 3.281179  3.0374346]
 [4.095189  3.7456043 4.0174284 3.757769 ]]


In [13]:
# 创建序列
j1: Tensor = tf.range(10)
tf.range(2, 20, 2)

<tf.Tensor: id=226, shape=(9,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int32)>

In [14]:
out: Tensor = tf.random.uniform([4, 10])
y: Tensor = tf.constant([2, 3, 2, 0])
y = tf.one_hot(y, depth=10)
loss = tf.keras.losses.mse(y, out)
loss = tf.reduce_mean(loss)
y

<tf.Tensor: id=238, shape=(4, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [15]:
z: Tensor = tf.random.normal([4, 2])
print(z)
b: Tensor = tf.ones(2)
z + b

tf.Tensor(
[[ 2.3675349  -0.02920443]
 [ 1.1152141  -0.42023924]
 [ 1.1338291   0.3902224 ]
 [-0.6729482  -0.28734776]], shape=(4, 2), dtype=float32)


<tf.Tensor: id=253, shape=(4, 2), dtype=float32, numpy=
array([[3.3675349 , 0.9707956 ],
       [2.115214  , 0.5797608 ],
       [2.133829  , 1.3902224 ],
       [0.32705182, 0.7126522 ]], dtype=float32)>

In [16]:
# 利用Dense()创建输入节点为4, 输出节点为3的线性层网络
fc: Dense = Dense(3)
fc.build(input_shape=(2, 4))
fc.bias    # 初始化偏置默认为0

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [17]:
# 索引
x = tf.random.normal([4, 32, 32, 3])
# print(x[0][1][2])

# 切片

# ::表示在行维度上读取所有行,相当于x[0]
x[0,::]

x[:, 0:28:2, 0:28:2, :]
x[...]
x[:2,...]
x[..., 2]
x[:1,..., 2]

<tf.Tensor: id=306, shape=(1, 32, 32), dtype=float32, numpy=
array([[[-2.187533  , -0.5890356 , -1.6013601 , ..., -0.2590891 ,
          0.76414436,  0.72559875],
        [ 1.1694764 , -0.54043555, -1.2284844 , ..., -0.538835  ,
          0.11262175,  0.57473   ],
        [-0.9801753 , -1.0150452 ,  0.06646056, ...,  1.7604659 ,
         -0.42706645, -2.096717  ],
        ...,
        [ 1.5884907 , -0.5820454 ,  2.4050667 , ..., -1.0554634 ,
          0.5594378 , -0.27278763],
        [ 1.7374376 , -1.2786231 ,  1.8127109 , ..., -0.656375  ,
          0.3775319 ,  0.14845076],
        [-0.42806068,  0.64354765, -1.3639857 , ..., -2.464225  ,
         -0.2645783 ,  2.8299336 ]]], dtype=float32)>

In [18]:
x = tf.range(96)

# reshape
tf.reshape(x, [2, 4, 4, 3])

y = tf.reshape(x, [2, -1, 3])

# expand_dims 只能增加长度为1的维度
tf.expand_dims(y, axis=1)

# squeeze 只能删除长度为1的维度
tf.squeeze(tf.expand_dims(y, axis=1), 1)

# squeeze不指定axis时，会删除所有长度为1的维度
tf.squeeze(tf.expand_dims(y, axis=1))



<tf.Tensor: id=322, shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]], dtype=int32)>

In [19]:
x:Tensor = tf.random.normal([2, 4, 4, 3])

# 交换维度
tf.transpose(x, perm=[1,0,3,2])

<tf.Tensor: id=330, shape=(4, 2, 3, 4), dtype=float32, numpy=
array([[[[ 0.5547775 , -0.6276764 , -0.91833484, -0.2513863 ],
         [-0.19137435, -0.13005817,  1.4231604 , -0.24842489],
         [-0.397956  ,  0.85827917,  1.0441968 ,  0.94798684]],

        [[-1.5056168 , -1.0201153 ,  1.1418942 , -1.0656655 ],
         [-0.5885998 ,  1.6457611 ,  0.9338937 ,  0.01569099],
         [ 0.4373556 , -0.39927006,  0.25680047,  0.14879677]]],


       [[[ 0.10939603,  0.8039543 , -2.1760561 , -0.38306615],
         [-0.08516815, -0.346964  , -0.1930268 , -2.164386  ],
         [-0.09546437,  0.7722759 , -0.15473597,  2.0647662 ]],

        [[ 0.21346037, -0.5597146 , -0.5211469 , -0.25029814],
         [-0.8953098 ,  0.5659693 ,  0.2565772 , -1.490601  ],
         [ 0.38352528, -1.7356949 , -0.21224697,  1.3413574 ]]],


       [[[ 0.586607  , -0.1585754 ,  0.48139757,  0.2445006 ],
         [-1.6100335 ,  0.2764863 ,  1.0218645 , -0.38982916],
         [-0.5771089 , -0.01834228,  0.75096

In [20]:
# tf.tile 拷贝维度
x = tf.constant([1,2])
y = tf.expand_dims(x, axis=0)
tf.tile(y, multiples=[3,2])

<tf.Tensor: id=335, shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]], dtype=int32)>

In [21]:
# tf.broadcast_to 轻量级别的维度复制
a: Tensor = tf.random.normal([4, 1])
tf.broadcast_to(a, [2, 2, 4, 2])

<tf.Tensor: id=343, shape=(2, 2, 4, 2), dtype=float32, numpy=
array([[[[-0.2345203 , -0.2345203 ],
         [ 0.14515573,  0.14515573],
         [ 0.04756442,  0.04756442],
         [-0.69616055, -0.69616055]],

        [[-0.2345203 , -0.2345203 ],
         [ 0.14515573,  0.14515573],
         [ 0.04756442,  0.04756442],
         [-0.69616055, -0.69616055]]],


       [[[-0.2345203 , -0.2345203 ],
         [ 0.14515573,  0.14515573],
         [ 0.04756442,  0.04756442],
         [-0.69616055, -0.69616055]],

        [[-0.2345203 , -0.2345203 ],
         [ 0.14515573,  0.14515573],
         [ 0.04756442,  0.04756442],
         [-0.69616055, -0.69616055]]]], dtype=float32)>

In [22]:
# 数学运算
a: Tensor = tf.constant([1, 2, 3])
b: Tensor = tf.constant([4, 5, 6])
    
a + b

a - b

a * b

a / b

a // b

tf.pow(a, b)

tf.square(a)

tf.sqrt(tf.cast(a, dtype=tf.float32))

tf.exp(1.)

tf.math.log(tf.exp(1.))

# 计算其他底数的对数可以用换底公式
tf.math.log(4.) / tf.math.log(2.)

# 矩阵乘法
a: Tensor = tf.random.normal([2, 4, 4,3])
b: Tensor = tf.random.normal([2, 4, 3, 15])
a @ b

<tf.Tensor: id=379, shape=(2, 4, 4, 15), dtype=float32, numpy=
array([[[[ 3.74404222e-01,  5.91449738e-02, -6.51759148e-01,
          -1.66513443e+00, -8.06431711e-01,  1.14377737e-01,
          -1.51322305e-01,  1.77743480e-01,  5.74115992e-01,
           3.97725075e-01, -1.05501747e+00, -1.28037468e-01,
          -3.53443265e-01,  1.31882519e-01, -1.01718390e+00],
         [-2.05502391e-01, -4.29294348e+00,  3.35740328e-01,
           1.44261611e+00,  1.42063653e+00, -1.34669733e+00,
          -6.86355710e-01, -7.06132650e-01, -1.60544217e-01,
           8.31396580e-01, -2.91474581e+00,  5.14380217e-01,
          -1.16204321e-01,  6.49828196e-01, -7.42595315e-01],
         [ 7.90771961e-01,  1.25905752e-01, -9.91329551e-01,
          -7.39583969e-01, -3.35029066e-01,  4.79518652e-01,
          -7.59226754e-02, -5.37409067e-01,  9.99447644e-01,
           1.32010627e+00, -1.80219054e+00,  9.45357382e-01,
          -2.39854127e-01, -6.77209422e-02,  3.33202899e-01],
         [ 2.102589

In [23]:
# 矩阵乘法broadcast机制
a: Tensor = tf.random.uniform([4, 28, 32])
b: Tensor = tf.random.uniform([32, 3])

a @ b

<tf.Tensor: id=394, shape=(4, 28, 3), dtype=float32, numpy=
array([[[ 9.872944 , 10.347326 ,  8.748014 ],
        [ 9.411736 ,  8.434071 ,  7.570074 ],
        [10.406382 ,  8.972353 ,  9.317976 ],
        [ 8.130375 ,  6.760029 ,  7.4854155],
        [ 8.785642 ,  8.480671 ,  7.626913 ],
        [ 8.884172 ,  8.222498 ,  7.304037 ],
        [ 9.78163  ,  9.047922 ,  8.182518 ],
        [ 9.818573 ,  7.9675193,  7.6332083],
        [10.794622 ,  8.162814 ,  8.692763 ],
        [ 8.634829 ,  7.681546 ,  7.4116573],
        [ 9.383492 ,  8.091636 ,  8.538621 ],
        [ 9.05339  ,  8.537532 ,  7.0001054],
        [ 9.265392 ,  7.144206 ,  8.328421 ],
        [ 9.7976265,  8.177673 ,  8.036125 ],
        [10.090645 ,  8.987413 ,  8.115154 ],
        [ 9.2985115,  6.8204107,  8.373852 ],
        [ 9.989695 ,  8.991512 ,  8.525156 ],
        [ 9.287579 ,  8.011543 ,  6.895021 ],
        [ 9.486481 ,  8.508483 ,  9.069126 ],
        [ 9.869941 ,  7.897554 ,  8.071772 ],
        [ 8.466901 ,

In [24]:
# 简单的前向传播算法计算流程
# 模拟MNIST数据集 训练三层神经网络 输入节点为784, 第一层输出节点256, 第二层输出节点数128, 第三层输出10
w1: Variable = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1: Variable = tf.Variable(tf.zeros([256]))
w2: Variable = tf.Variable(tf.random.truncated_normal([256, 128], stddev=0.1))
b2: Variable = tf.Variable(tf.zeros([128]))
w3: Variable = tf.Variable(tf.random.truncated_normal([128, 10], stddev=0.1))
b3: Variable = tf.Variable(tf.zeros([10]))
    
# 先转换输入值的维度
x: Tensor = tf.random.normal([30, 28, 28])
x = tf.reshape(x, [30, -1])

h1 = x @ w1 + tf.broadcast_to(b1, [30, 256])
h1 = tf.nn.relu(h1)

h2 = h1 @ w2 + tf.broadcast_to(b2, [h1.shape[0], 128])
h2 = tf.nn.relu(h2)

h3 = h2 @ w3 + tf.broadcast_to(b3, [h2.shape[0], 10])
out = tf.nn.relu(h3)
