In [1]:
import numpy as np
import tensorflow as tf

from tensorflow import Tensor, Variable
from typing import Dict, List

In [8]:
# 合并(合并操作可以在任意维度上进行, 唯一的约束是非合并维度的长度必须一致/ 不会创建新维度)
a: Tensor = tf.random.normal([4, 35, 8])
b: Tensor = tf.random.normal([6, 35, 8])
    
tf.concat([a, b], axis=0)

<tf.Tensor: id=80, shape=(10, 35, 8), dtype=float32, numpy=
array([[[-1.10452664e+00, -2.02109292e-02,  3.30053806e-01, ...,
         -1.15177107e+00, -9.21432450e-02, -4.01801080e-01],
        [ 1.16523600e+00,  1.13439357e+00, -1.37961292e+00, ...,
         -1.90729514e-01,  1.58941042e+00,  8.41974616e-01],
        [ 6.22450650e-01,  9.04628992e-01, -1.77025747e+00, ...,
         -7.00301230e-01, -1.18159497e+00,  5.51147223e-01],
        ...,
        [ 1.66584909e+00, -2.10374880e+00, -6.81574225e-01, ...,
         -8.06406260e-01,  1.37447989e+00, -3.84866804e-01],
        [ 1.68069875e+00, -5.42640567e-01, -3.94110262e-01, ...,
         -1.17503250e+00, -4.24529542e-04, -1.29370010e+00],
        [-7.53534213e-02,  3.75501513e-01,  3.41359526e-01, ...,
         -9.13397729e-01, -8.08164239e-01, -1.06215549e+00]],

       [[ 1.17600989e+00,  5.16927898e-01, -8.64575446e-01, ...,
         -2.91603178e-01, -6.14499211e-01,  4.95150387e-01],
        [-3.10593396e-01,  7.88977981e-01, 

In [13]:
# 合并时,需要创建新维度用tf.stack
a: Tensor = tf.random.normal([35, 4])
b: Tensor = tf.random.normal([35, 4])
    
tf.stack([a, b], axis=0)

<tf.Tensor: id=145, shape=(2, 35, 4), dtype=float32, numpy=
array([[[ 0.08992425, -0.10304821,  0.63352484,  1.8902451 ],
        [-0.71967506,  0.99226296,  2.0740726 ,  2.106621  ],
        [-0.9310499 ,  2.6675143 , -0.58506554, -0.35312146],
        [-0.6340968 , -0.09989558, -1.5757642 , -0.55531377],
        [-1.1561148 , -0.48777187,  1.1236368 , -0.24014884],
        [-0.5347527 , -0.9835442 ,  1.1116341 ,  1.2970514 ],
        [ 0.3419801 ,  0.5158874 ,  0.8493912 , -0.3297201 ],
        [ 0.37757072, -0.75276965,  0.03503805, -0.06943581],
        [ 0.7300287 , -1.6213628 , -0.42331773,  0.2831587 ],
        [-0.01989626,  2.3085806 , -0.15460324,  0.23136742],
        [ 0.35188448, -0.8350485 , -0.42455146,  0.44023225],
        [-0.15992433,  1.2440671 ,  1.1906718 ,  1.3696909 ],
        [-1.4320234 ,  0.32104325, -0.3532241 , -1.3196822 ],
        [-1.1299471 ,  0.30506673, -0.4702562 ,  1.5196971 ],
        [-0.09943678, -0.75399953, -1.1360723 ,  1.0920311 ],
        [ 

In [28]:
# 分割
x: Tensor = tf.random.normal([10, 35, 8])

# 等长切割
z1: List[Tensor] = tf.split(x, axis=0, num_or_size_splits=10)
z2: List[Tensor] = tf.split(x, axis=1, num_or_size_splits=[30, 5])

<tf.Tensor: id=348, shape=(10, 30, 8), dtype=float32, numpy=
array([[[ 1.6462111 , -1.3046247 , -1.1761162 , ...,  0.18955803,
          0.86263704,  0.35289866],
        [-0.33641583, -1.6733015 ,  1.674013  , ...,  0.01789249,
          1.9411451 ,  1.4143919 ],
        [-1.5293717 , -1.5646148 , -1.2105379 , ..., -1.4999635 ,
         -0.18249342,  0.70913655],
        ...,
        [ 1.0226523 , -0.13796072,  0.6910236 , ...,  0.55605966,
          0.73312944, -0.26801458],
        [ 0.26690713,  0.9215036 , -0.86981124, ...,  0.56822765,
          0.8857658 ,  1.5466594 ],
        [-0.8192537 , -1.6761295 , -0.8084229 , ...,  0.1460883 ,
          1.3324956 ,  0.7457897 ]],

       [[ 0.9262078 ,  0.6235281 ,  0.80516624, ..., -1.045489  ,
          0.01816856, -0.74369025],
        [ 0.43920898,  1.2582994 ,  1.1860312 , ..., -0.9740584 ,
         -2.0910208 ,  0.6840514 ],
        [ 0.2617508 , -1.4119422 ,  0.64348686, ...,  0.16597943,
          0.0812083 ,  1.339266  ],
      

In [30]:
# 如果希望在某个维度上全部按长度为1的方式分割, 可直接用tf.unstack(会降一个维度)
x: Tensor = tf.random.normal([10, 35, 8])
tf.unstack(x, axis=0)

[<tf.Tensor: id=362, shape=(35, 8), dtype=float32, numpy=
 array([[-1.01810031e-01, -3.35331440e-01,  1.19366539e+00,
          1.29909232e-01,  1.82670262e-02, -9.79491115e-01,
          3.67989033e-01, -1.49154234e+00],
        [ 6.04271889e-01,  8.69210660e-01, -2.64134377e-01,
          9.47295606e-01,  1.54449248e+00,  8.94546330e-01,
          1.32473385e+00, -5.32079756e-01],
        [ 6.99282587e-01,  7.17553735e-01,  1.50174022e+00,
          1.64788783e-01,  7.47011125e-01, -3.98684561e-01,
         -3.72463495e-01, -9.54419553e-01],
        [ 1.76357329e-01, -1.96578562e-01, -6.94436073e-01,
          1.12459564e+00,  1.44100606e-01, -1.56865001e-01,
          9.12977517e-01, -4.38681334e-01],
        [-7.53937304e-01, -5.83005190e-01,  8.77498865e-01,
         -6.31454051e-01, -2.92339653e-01,  4.04141247e-01,
         -8.48775625e-01,  3.16291377e-02],
        [-2.23355234e-01, -2.57526249e-01, -1.75925004e+00,
          6.58226907e-01,  2.48351023e-01, -1.11499763e+00,
  

In [4]:
# 范数
x: Tensor = tf.ones([2, 2])
print(x)
    
# 1-范数
tf.norm(x, ord=1)
print(f"1-范数: {tf.norm(x, ord=1)}")

# 2-范数
tf.norm(x, ord=2)
print(f"2-范数: {tf.norm(x, ord=2)}")

# ∞-范数
tf.norm(x, ord=np.inf)
print(f"∞-范数: {tf.norm(x, ord=np.inf)}")

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
1-范数: 4.0
2-范数: 2.0
∞-范数: 1.0


In [8]:
# 求某个维度上最大最小、均值、和
x: Tensor = tf.random.normal([4, 10, 3])
    
tf.reduce_max(x, axis=0)
print(f"0维度的最大值: {tf.reduce_max(x, axis=0)}")

tf.reduce_min(x, axis=0)

tf.reduce_mean(x, axis=0)

tf.reduce_sum(x, axis=2)

0维度的最大值: [[1.3107772  0.952024   1.710042  ]
 [0.8157115  1.2754475  1.19682   ]
 [1.5048692  0.71222216 1.0211705 ]
 [0.6867241  0.5375618  1.7849402 ]
 [1.245758   0.6546595  0.12074998]
 [0.14838834 0.83765477 2.078682  ]
 [0.81409264 0.34474733 1.1351956 ]
 [0.6053924  0.176261   2.0573406 ]
 [0.9540095  0.97631264 1.0708348 ]
 [0.40874687 0.95338124 1.0058855 ]]


<tf.Tensor: id=148, shape=(4, 10), dtype=float32, numpy=
array([[ 1.0457039 , -2.1087928 ,  0.5120994 ,  2.199227  ,  0.3635968 ,
        -1.9884084 , -2.2417355 ,  1.1847732 ,  1.1653031 ,  2.3680136 ],
       [ 1.1211705 ,  2.0890503 ,  2.5808554 , -2.6535673 ,  0.06472754,
         1.8366234 , -0.8142642 , -2.6675344 , -1.4992706 , -0.61929107],
       [-0.8509166 ,  1.0703616 ,  0.6933477 , -2.00246   ,  0.31853563,
         0.4269832 ,  2.257641  , -1.4839323 , -2.2663329 , -0.78552485],
       [ 0.30089164, -0.64803743, -2.442026  ,  0.8633468 ,  1.0595764 ,
        -0.25989157, -2.8070579 , -1.8053908 ,  3.0011568 ,  1.5525512 ]],
      dtype=float32)>

In [11]:
out: Tensor = tf.random.normal([4, 10])  # 预测输出
print(f"out: \n{out}")
y: Tensor = tf.constant([1, 2, 2, 0])    # 真实标签
y = tf.one_hot(y, depth=10)
print(f"经过独热编码后的真实标签: \n{y}")

print(f"validate: {tf.norm((out[0]-y[0]), ord=2)**2 /10}")

loss = tf.keras.losses.mse(y, out)
loss


out: 
[[ 7.53424644e-01  1.92473698e+00 -1.36847377e+00  1.00065899e+00
   1.80770898e+00 -7.62459636e-01  6.32182181e-01  1.41463590e+00
  -5.89448094e-01  1.78159046e+00]
 [-6.24765754e-01 -1.25157833e+00 -1.08588505e+00  3.35644007e-01
  -5.37756503e-01  1.67031884e+00  1.02824652e+00  2.32417062e-01
   3.97801876e-01 -3.86259854e-01]
 [ 4.05512184e-01 -5.21701872e-01  3.25052202e-01 -1.50585920e-03
   7.09055483e-01 -1.76308274e+00 -2.34169483e+00 -1.30147541e+00
  -1.10026836e+00 -5.31229198e-01]
 [-2.34472656e+00  2.51842797e-01  1.10163224e+00 -4.87131864e-01
  -1.76830128e-01  1.35117781e+00 -1.07346706e-01  1.52392626e+00
   7.57026315e-01 -1.12972960e-01]]
经过独热编码后的真实标签: 
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
validate: 1.406834363937378


<tf.Tensor: id=244, shape=(4,), dtype=float32, numpy=array([1.4068345, 1.0918252, 1.3173559, 1.747819 ], dtype=float32)>

#### tf.nn.sotfmax 是一种归一化方式

In [16]:
# 获取最值所在的索引号
out: Tensor = tf.random.normal([2, 10])
print(f"out: \n{out}")

out = tf.nn.softmax(out, axis=1)
print(f"out after softmax: \n{out}")

tf.argmax(out, axis=1)

out: 
[[-0.95118797 -0.51625746 -0.83433646  1.7843875   1.0589265  -0.4728893
  -0.60878503  1.3728456  -0.8489586  -0.26074722]
 [-1.5103331   0.7149343   1.5535059  -0.14795662 -0.21622576  1.1663598
   0.0308446   1.1381786  -0.6284299  -0.52855873]]
out after softmax: 
[[0.02331422 0.0360171  0.02620407 0.3594729  0.17402132 0.03761346
  0.03283406 0.23819675 0.0258237  0.0465024 ]
 [0.01287939 0.11921106 0.2757424  0.05029998 0.04698063 0.18722685
  0.06014786 0.18202424 0.03111006 0.03437751]]
tf.Tensor([1.         0.99999994], shape=(2,), dtype=float32)


<tf.Tensor: id=297, shape=(2,), dtype=int64, numpy=array([3, 2])>

In [17]:
# 张量比较
out: Tensor = tf.random.normal([100, 10])
out = tf.nn.softmax(out, axis=1)
pred: Tensor = tf.argmax(out, axis=1)

y: Tensor = tf.random.uniform([100], dtype=tf.int64, maxval=10)
print(f"y: \n{y}")

z: Tensor = tf.equal(pred, y)
print(f"bool: {z}")

# 统计True的个数(先将bool转换成int, 然后利用sum来统计True的个数)
tf.reduce_sum(tf.cast(z, dtype=tf.int16))
 

y: 
[4 9 2 1 0 5 7 6 1 9 7 8 3 1 8 3 2 8 3 0 0 2 9 8 5 5 0 8 6 3 0 9 6 1 9 2 4
 6 1 0 4 6 8 6 5 0 2 9 1 7 3 4 6 5 7 7 1 8 8 7 0 7 2 6 5 7 5 0 7 0 2 7 5 6
 0 4 3 1 8 8 6 5 9 6 7 7 5 9 3 5 3 6 6 2 1 5 5 5 6 1]
bool: [False False False False False False False False False False False False
 False False False False False False  True False False False False False
 False False False False False False False False False False False False
 False False False  True False False  True False False False False False
 False False False False False False False False False False False False
 False False  True False False False False False False False False False
  True False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False]


<tf.Tensor: id=314, shape=(), dtype=int16, numpy=6>

In [106]:
# 填充

a: Tensor = tf.constant([1, 2, 3, 4, 5, 6])
b: Tensor = tf.constant([7, 8, 1, 6])

b = tf.pad(b, paddings=[[0, 2]])

tf.stack([a, b], axis=0)

<tf.Tensor: id=1184, shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [7, 8, 1, 6, 0, 0]], dtype=int32)>

In [19]:
# 数据限幅

a: Tensor = tf.range(9)
print(f"a: \n{a}")    

tf.maximum(a, 5)        # 下限幅为5
print(f"tf.maximum: \n{tf.maximum(a, 5)}")

tf.minimum(a, 5)        # 上限幅为5
print(f"tf.minimum: \n{tf.minimum(a, 5)}")

tf.clip_by_value(a, 2, 7)

a: 
[0 1 2 3 4 5 6 7 8]
tf.maximum: 
[5 5 5 5 5 5 6 7 8]
tf.minimum: 
[0 1 2 3 4 5 5 5 5]


<tf.Tensor: id=346, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7], dtype=int32)>

In [27]:
# 假设有4个班级, 每个班有35个学生, 8门科目
x = tf.random.uniform([4, 35, 8], maxval=100, dtype=tf.int32)
print(f"x: \n{x}")

# tf.gather适合没有规则的场景
# 查看第1、2班级的成绩
x1 = tf.gather(x, [1, 2], axis=0)
print(f"x1: \n{x1}")

# tf.gather_nd多维度收集数据
x2 = tf.gather_nd(x, [[1, 1], [2, 2], [3, 3]])
print(f"x2: \n{x2}")

x: 
[[[69 85 65 ... 92 46 41]
  [33 18 15 ...  3 43  7]
  [75 89 22 ... 88 75 61]
  ...
  [13  6 57 ... 21 14  3]
  [43 16 43 ... 83 89 36]
  [52  4 12 ...  6  3 87]]

 [[99 42  1 ...  9 82 77]
  [97 27 65 ... 12 69 55]
  [65 93 89 ... 77 50 38]
  ...
  [30 59 84 ... 87 56 51]
  [ 7  1 33 ...  7 75  3]
  [ 2 61 38 ... 24 56 66]]

 [[96 63 22 ... 77 45 96]
  [27 47 72 ... 45 38 44]
  [57 49 78 ... 66 23 57]
  ...
  [58 10 92 ... 15 18 50]
  [20 77 87 ... 25 12 74]
  [55 66 87 ... 20 50 78]]

 [[ 9 45 52 ... 10  0 16]
  [91 15  7 ... 35  6 82]
  [12 23 70 ... 49 62 14]
  ...
  [81 24 12 ... 81 22 96]
  [31 58 28 ... 92 30 62]
  [52  6 66 ... 48  5 69]]]
x1: 
[[[99 42  1 77 43  9 82 77]
  [97 27 65 32 78 12 69 55]
  [65 93 89 85 37 77 50 38]
  [93 74 21 18 17 72 70 10]
  [87 29 94 88 24  1 32  8]
  [53 48 90  3 32 49  3 94]
  [75 78  0 67 94 68  4 78]
  [70 26  2 61 40 22 18 43]
  [41 67 85 81 17 97 88 93]
  [81 61  1  4 58 27 47 69]
  [47 86 17 14  6 12 14 99]
  [90 71 28 48 95 57 41 58]

In [30]:
#tf.boolean_mask
tf.boolean_mask(x, mask=[True, False, True, False], axis=0)

<tf.Tensor: id=446, shape=(2, 35, 8), dtype=int32, numpy=
array([[[69, 85, 65, 38, 19, 92, 46, 41],
        [33, 18, 15,  9, 72,  3, 43,  7],
        [75, 89, 22, 73, 70, 88, 75, 61],
        [33, 51, 34, 42, 76, 55, 57, 63],
        [99, 23, 18, 28, 42,  4, 13, 33],
        [88, 50, 26, 42, 91, 43,  5, 88],
        [87, 88,  5, 75, 95, 46, 27, 89],
        [61, 84,  4, 71, 39, 65, 98, 36],
        [87, 32, 41, 57, 66,  3, 59, 32],
        [18, 45, 90, 26, 13, 33,  4, 36],
        [60, 92, 62, 31, 67, 44, 50,  7],
        [72,  6, 36, 76, 78, 43, 52, 46],
        [19, 35,  1, 92,  2, 50, 41, 41],
        [15,  4, 65,  0, 27, 66, 29, 23],
        [ 8, 17,  3, 34, 54,  5,  2, 91],
        [71, 24, 33, 48, 49, 28, 68, 66],
        [91, 61, 55, 12, 94, 56, 79, 96],
        [43, 38, 31, 48, 43, 50, 90, 13],
        [75, 18, 90, 47, 85,  0, 66, 18],
        [ 0, 43, 45,  5, 26, 66, 91, 32],
        [85, 23, 35, 81, 23, 44,  1, 22],
        [31, 23, 73, 55, 94, 36, 13, 86],
        [43, 44, 6

In [34]:
a: Tensor = tf.ones([3, 3])
b: Tensor = tf.zeros([3, 3])

cond: tf.constant = tf.constant([[True, False, False], [False, False, True], [False, True, True]])
x1: Tensor = tf.where(cond, a, b)
print(f"x1: \n{x1}")

# 若a、b为None时, tf.where will return index of true in cond
x2: Tensor = tf.where(cond)
print(f"x2: \n{x2}")

x1: 
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 1.]]
x2: 
[[0 0]
 [1 2]
 [2 1]
 [2 2]]


In [39]:
z = tf.random.normal([3,3])

tf.boolean_mask(z, z>0)


<tf.Tensor: id=598, shape=(3,), dtype=float32, numpy=array([0.67334086, 0.8210211 , 0.07181786], dtype=float32)>

In [40]:
indices: Tensor = tf.constant([[4], [3], [1], [7]])
updates: Tensor = tf.constant([4.4, 3.3, 1.1, 7.7])

tf.scatter_nd(indices, updates, [8])

<tf.Tensor: id=602, shape=(8,), dtype=float32, numpy=array([0. , 1.1, 0. , 3.3, 4.4, 0. , 0. , 7.7], dtype=float32)>